### ISSUE TITLE
Fix header ID values returned from Queries.addRequest.

### ISSUE THREAD

**Issue by ClintCombs** [ClintCombs/regrest#22]
Queries.addRequest(tp: TestPlan, req: Request): Future[Request] currently does not return valid header IDs. Fix this and update this line in QueriesSpec.scala:

    // TODO: queries.addRequest(tp: TestPlan, req: Request): Future[Request] does not yet return header IDs
    if (false) requests must contain(newRequest2)

**Comment by ClintCombs** [comment]
List(Request(RequestCore(3,3,,http://example.com/3/2,,None,None,None),Vector(Header(1,3,Content-Type,application/xml), Header(2,3,Accept,text/plain))), Request(RequestCore(2,3,,http://example.com/3/1,,None,None,None),Vector())) did not contain element Request(RequestCore(3,3,,http://example.com/3/2,,None,None,None),List(Header(0,3,Content-Type,application/xml), Header(0,3,Accept,text/plain)))
ScalaTestFailureLocation: org.regrest.db.specs.QueriesSpec$$anonfun$1$$anonfun$apply$mcV$sp$7 at (QueriesSpec.scala:160)
org.scalatest.exceptions.TestFailedException: List(Request(RequestCore(3,3,,http://example.com/3/2,,None,None,None),Vector(Header(1,3,Content-Type,application/xml), Header(2,3,Accept,text/plain))), Request(RequestCore(2,3,,http://example.com/3/1,,None,None,None),Vector())) did not contain element Request(RequestCore(3,3,,http://example.com/3/2,,None,None,None),List(Header(0,3,Content-Type,application/xml), Header(0,3,Accept,text/plain)))
    	at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
    	at org.scalatest.MustMatchers$MustMethodHelper$.mustMatcher(MustMatchers.scala:6231)
    	at org.scalatest.MustMatchers$AnyMustWrapper.must(MustMatchers.scala:6277)
    	at org.regrest.db.specs.QueriesSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply$mcV$sp(QueriesSpec.scala:160)
    	at org.regrest.db.specs.QueriesSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(QueriesSpec.scala:118)
    	at org.regrest.db.specs.QueriesSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(QueriesSpec.scala:118)
    	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
    	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    	at org.scalatest.Transformer.apply(Transformer.scala:22)
    	at org.scalatest.Transformer.apply(Transformer.scala:20)
    	at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:953)
    	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
    	at org.scalatest.WordSpec.withFixture(WordSpec.scala:1881)
    	at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:950)
    	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
    	at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:962)
    	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    	at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:962)
    	at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
    	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
    	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1021)
    	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
    	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    	at scala.collection.immutable.List.foreach(List.scala:318)
    	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
    	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
    	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
    	at scala.collection.immutable.List.foreach(List.scala:318)
    	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
    	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
    	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1021)
    	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
    	at org.scalatest.Suite$class.run(Suite.scala:1424)
    	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
    	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
    	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1067)
    	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
    	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1067)
    	at org.regrest.specs.RegrestSpec.org$scalatest$BeforeAndAfterAll$$super$run(RegrestSpec.scala:7)
    	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
    	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
    	at org.regrest.specs.RegrestSpec.run(RegrestSpec.scala:7)
    	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
    	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
    	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
    	at scala.collection.immutable.List.foreach(List.scala:318)
    	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
    	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
    	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
    	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
    	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
    	at org.scalatest.tools.Runner$.run(Runner.scala:883)
    	at org.scalatest.tools.Runner.run(Runner.scala)
    	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
    	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
